"""Per-architecture wiring diagrams generated by plot_model."""

from _style import FIG


def main() -> None:
    import resdag as rd

    out = FIG / "architectures"
    out.mkdir(parents=True, exist_ok=True)
    factories = {
        "classic_esn": lambda: rd.models.classic_esn(64, 3, 3),
        "ott_esn": lambda: rd.models.ott_esn(64, 3, 3),
        "power_augmented": lambda: rd.models.power_augmented(64, 3, 3),
        "linear_esn": lambda: rd.models.linear_esn(64, 3),
        "headless_esn": lambda: rd.models.headless_esn(64, 3),
    }
    for name, make in factories.items():
        make().plot_model(show_shapes=False, rankdir="LR",
                          save_path=str(out / f"{name}.svg"), format="svg")
        print(f"  wrote architectures/{name}.svg")


if __name__ == "__main__":
    main()
