"""Architecture diagrams — generated by the library's own ``plot_model``.

Includes simple-to-complex examples used in
``docs/guides/visualizing-architectures.md`` and the home page.
"""

from __future__ import annotations

import pytorch_symbolic as ps

import resdag as rd
from resdag.layers import (
    CGReadoutLayer,
    Concatenate,
    ESNLayer,
    NGReservoir,
    Power,
    SelectiveExponentiation,
)

from ._common import OUT


def _save_svg(model: rd.ESNModel, name: str, **plot_kwargs) -> None:
    src = model.plot_model(show_shapes=False, show_trainable=False,
                           rankdir="LR", **plot_kwargs)
    try:
        svg = src.pipe(format="svg")  # type: ignore[union-attr]
    except Exception as exc:  # pragma: no cover
        print(f"  ! {name}: graphviz unavailable ({exc})")
        return
    path = OUT / name
    path.write_bytes(svg)
    print(f"  ✓ {path.relative_to(OUT.parents[2])}")


# ----- premade factories --------------------------------------------------- #

def arch_classic_esn() -> None:
    _save_svg(
        rd.classic_esn(reservoir_size=200, feedback_size=3, output_size=3),
        "arch_classic_esn.svg",
    )


def arch_ott_esn() -> None:
    _save_svg(
        rd.ott_esn(reservoir_size=200, feedback_size=3, output_size=3),
        "arch_ott_esn.svg",
    )


def arch_power_augmented() -> None:
    _save_svg(
        rd.power_augmented(reservoir_size=200, feedback_size=3,
                           output_size=3, exponent=2.0),
        "arch_power_augmented.svg",
    )


def arch_ngrc() -> None:
    inp = rd.reservoir_input(3)
    ngrc = NGReservoir(input_dim=3, k=2, s=1, p=2)
    features = ngrc(inp)
    out = CGReadoutLayer(in_features=ngrc.feature_dim,
                         out_features=3, name="output")(features)
    _save_svg(rd.ESNModel(inp, out), "arch_ngrc.svg")


# ----- progression: simple → complex (visualizing-architectures.md) ------ #

def arch_minimal() -> None:
    """Single reservoir + readout — the simplest possible ResDAG model."""
    inp = rd.reservoir_input(1)
    res = ESNLayer(reservoir_size=100, feedback_size=1)(inp)
    out = CGReadoutLayer(100, 1, name="output")(res)
    _save_svg(rd.ESNModel(inp, out), "arch_minimal.svg")


def arch_input_driven() -> None:
    """Feedback + exogenous driver."""
    feedback = rd.reservoir_input(3)
    driver = rd.reservoir_input(2)
    res = ESNLayer(reservoir_size=300, feedback_size=3, input_size=2)(feedback, driver)
    out = CGReadoutLayer(300, 3, name="output")(res)
    _save_svg(rd.ESNModel([feedback, driver], out), "arch_input_driven.svg")


def arch_multi_readout() -> None:
    """One reservoir, two readout heads."""
    inp = rd.reservoir_input(3)
    res = ESNLayer(reservoir_size=400, feedback_size=3)(inp)
    head_position = CGReadoutLayer(400, 3, name="position")(res)
    head_velocity = CGReadoutLayer(400, 3, name="velocity")(res)
    _save_svg(rd.ESNModel(inp, [head_position, head_velocity]),
              "arch_multi_readout.svg")


def arch_parallel_reservoirs() -> None:
    """Two reservoirs in parallel, outputs concatenated before readout."""
    inp = rd.reservoir_input(3)
    fast = ESNLayer(reservoir_size=200, feedback_size=3,
                    spectral_radius=0.6, leak_rate=1.0)(inp)
    slow = ESNLayer(reservoir_size=200, feedback_size=3,
                    spectral_radius=0.95, leak_rate=0.3)(inp)
    merged = Concatenate()(fast, slow)
    out = CGReadoutLayer(400, 3, name="output")(merged)
    _save_svg(rd.ESNModel(inp, out), "arch_parallel_reservoirs.svg")


def arch_augmented_deep() -> None:
    """Reservoir → power augmentation → skip-connected concatenation."""
    inp = rd.reservoir_input(3)
    res = ESNLayer(reservoir_size=400, feedback_size=3)(inp)
    pow_aug = Power(exponent=2.0)(res)
    sel_aug = SelectiveExponentiation(index=1, exponent=3.0)(res)
    merged = Concatenate()(inp, res, pow_aug, sel_aug)
    out = CGReadoutLayer(merged.shape[-1], 3, name="output")(merged)
    _save_svg(rd.ESNModel(inp, out), "arch_augmented_deep.svg")


def main() -> None:
    print("Architectures …")
    arch_classic_esn()
    arch_ott_esn()
    arch_power_augmented()
    arch_ngrc()
    arch_minimal()
    arch_input_driven()
    arch_multi_readout()
    arch_parallel_reservoirs()
    arch_augmented_deep()


if __name__ == "__main__":
    main()
