"""Golden-trajectory forecast regression test per premade model (issue #401).

Locks the behavioural contract of :meth:`resdag.core.ESNModel.forecast` for the
forecast-capable premade models — ``classic_esn``, ``ott_esn``,
``power_augmented`` — plus an NG-RC forecaster, so a silent regression in the
forecast path fails CI.  The forecast path has been re-fixed several times
(slot-0, the warmup/forecast seam, the flat single-step engine) with nothing
pinning the *output*; this test pins it.

For each model a fully-seeded build (``seed=`` deterministically fixes every
reservoir parameter) is trained on a canonical Lorenz-63 series in CPU
``float64`` and asserted against a committed golden:

- **Prefix match** — the first ``prefix_steps`` forecast steps equal the golden
  within a tight tolerance.  This is the structural guard: the historical
  regressions shift these steps by order 0.1–1, far above cross-platform BLAS /
  CG noise.
- **VPT floor** — the Valid Prediction Time against the true continuation clears
  a committed, margin-padded floor (a coarse "quality did not collapse" guard).

Everything (specs, data, metric, tolerances) lives in
:mod:`tests.test_models.golden_forecast`; the fixtures live under
``tests/fixtures/golden_forecast/`` and are (re)generated by
``tools/regen_golden_forecasts.py``.  The whole module runs in the normal
(non-slow) suite in ~2 s on CPU.
"""

from __future__ import annotations

from collections.abc import Callable

import numpy as np
import pytest
import torch

from .golden_forecast import (
    FIXTURE_VERSION,
    FIXTURES_DIR,
    HORIZON,
    SPECS,
    GoldenSpec,
    load_fixture,
    make_lorenz_splits,
    train_and_forecast,
    valid_prediction_time,
)

SPEC_BY_NAME: dict[str, GoldenSpec] = {spec.name: spec for spec in SPECS}


@pytest.fixture(scope="module")
def splits():
    """The canonical Lorenz-63 splits, computed once for the module."""
    return make_lorenz_splits()


@pytest.fixture(scope="module")
def forecast_for(splits) -> Callable[[str], torch.Tensor]:
    """Return a lazy, cached ``name -> live forecast`` accessor.

    Each model is built/trained/forecast at most once per test session, the
    first time a test asks for it.
    """
    cache: dict[str, torch.Tensor] = {}

    def _get(name: str) -> torch.Tensor:
        if name not in cache:
            spec = SPEC_BY_NAME[name]
            cache[name] = train_and_forecast(spec.builder(), splits)
        return cache[name]

    return _get


@pytest.mark.parametrize("spec", SPECS, ids=lambda s: s.name)
class TestGoldenForecast:
    """The committed golden trajectory + VPT floor must reproduce per model."""

    def test_forecast_shape_and_finite(self, spec: GoldenSpec, forecast_for) -> None:
        """The forecast is ``(1, HORIZON, 3)`` and entirely finite."""
        live = forecast_for(spec.name)
        assert isinstance(live, torch.Tensor)
        assert live.shape == (1, HORIZON, 3)
        assert torch.isfinite(live).all()

    def test_prefix_matches_golden(self, spec: GoldenSpec, forecast_for) -> None:
        """The first ``prefix_steps`` forecast steps match the committed golden.

        This is the precise behavioural guard.  A regression in the forecast
        path (slot-0, the warmup/forecast seam, the flat engine, augmentation
        wiring) shifts these steps far beyond the tolerance; cross-platform
        numerical noise stays well below it.
        """
        golden, meta = load_fixture(spec.name)
        live = forecast_for(spec.name).detach().cpu().double().numpy()
        k = int(meta["prefix_steps"])
        np.testing.assert_allclose(
            live[:, :k],
            golden[:, :k],
            atol=float(meta["prefix_atol"]),
            rtol=float(meta["prefix_rtol"]),
            err_msg=(
                f"{spec.name}: forecast prefix drifted from the committed golden. "
                "If this change to the forecast path is intentional, regenerate with "
                "`python tools/regen_golden_forecasts.py --all` and review the diff."
            ),
        )

    def test_vpt_clears_floor(self, spec: GoldenSpec, forecast_for, splits) -> None:
        """The live forecast's Valid Prediction Time clears the committed floor."""
        _, _, _, _, val = splits
        golden, meta = load_fixture(spec.name)
        live = forecast_for(spec.name)
        measured = valid_prediction_time(live, val, threshold=float(meta["vpt_threshold"]))
        floor = int(meta["vpt_floor"])
        assert measured >= floor, (
            f"{spec.name}: VPT collapsed to {measured} (floor {floor}). "
            "Forecast quality regressed, or regenerate the golden if intended."
        )

    def test_golden_matches_truth_within_its_own_vpt(self, spec: GoldenSpec, splits) -> None:
        """Sanity: the committed golden itself is a real forecast of the truth.

        Guards against a fixture that was generated from a broken model — the
        stored trajectory must track the true Lorenz continuation for at least
        the floor's worth of steps.
        """
        _, _, _, _, val = splits
        golden, meta = load_fixture(spec.name)
        golden_vpt = valid_prediction_time(
            torch.as_tensor(golden), val, threshold=float(meta["vpt_threshold"])
        )
        assert golden_vpt >= int(meta["vpt_floor"])


class TestFixtureIntegrity:
    """The committed fixture set stays in lockstep with the model specs."""

    def test_every_spec_has_a_fixture(self) -> None:
        """Adding a model spec without regenerating its fixture fails loudly."""
        for spec in SPECS:
            golden, meta = load_fixture(spec.name)
            assert golden.shape == (1, HORIZON, 3)
            assert meta["name"] == spec.name
            assert int(meta["fixture_version"]) == FIXTURE_VERSION

    def test_no_orphan_fixtures(self) -> None:
        """Every committed ``.npz`` corresponds to a current spec."""
        committed = {p.stem for p in FIXTURES_DIR.glob("*.npz")}
        expected = {spec.name for spec in SPECS}
        assert committed == expected, (
            f"orphan/missing fixtures: extra={committed - expected}, missing={expected - committed}. "
            "Regenerate with `python tools/regen_golden_forecasts.py --all`."
        )
