"""06 — Forecasting: two-phase autoregression, drivers, multi-output.

``ESNModel.forecast()`` runs in two phases:

    Phase 1 (warmup)    teacher-forced pass over real data to synchronize
                        the reservoir state (Echo State Property)
    Phase 2 (forecast)  the model's own output becomes its next feedback
                        input for ``horizon`` steps

What it shows
-------------
1. Train + two-phase forecast on a smooth signal
2. return_warmup: prepending the teacher-forced outputs
3. Drivers with CORRECT time alignment: forecast drivers start right
   after the warmup window and have horizon-1 steps
4. Multi-output models: the first output is the feedback

Expected runtime: ~5 s on CPU.

Run with ``--plot`` to visualize section 1 (matplotlib optional).
"""

import sys

import torch

import resdag as rd
from resdag.core import ESNModel, Input
from resdag.layers import CGReadoutLayer, ESNLayer
from resdag.training import ESNTrainer


def main() -> None:
    torch.manual_seed(42)

    # ------------------------------------------------------------------
    # 1. Two-phase forecast on a quasi-periodic signal
    # ------------------------------------------------------------------
    print("=" * 70)
    print("1. Two-phase forecast")
    print("=" * 70)

    # Quasi-periodic scalar signal: sum of two incommensurate sines
    t = torch.arange(1500, dtype=torch.float32)
    series = (0.6 * torch.sin(0.07 * t) + 0.4 * torch.sin(0.02 * torch.pi * t)).reshape(1, -1, 1)
    # series: (1, 1500, 1) = (batch, time, features)

    warmup = series[:, :200]  # sync the reservoir
    train_in = series[:, 200:1000]
    train_tgt = series[:, 201:1001]  # next-step target
    f_warmup = series[:, 800:1000]  # warmup for forecasting = tail of train
    truth = series[:, 1000:1300]  # what we try to reproduce

    # Slow leak + spectral radius near 1: long memory for slow oscillations
    model = rd.classic_esn(300, feedback_size=1, output_size=1, spectral_radius=0.99, leak_rate=0.1)
    ESNTrainer(model).fit((warmup,), (train_in,), {"output": train_tgt})

    horizon = truth.shape[1]
    preds = model.forecast(f_warmup, horizon=horizon)  # (1, 300, 1)
    mse = torch.mean((preds - truth) ** 2).item()
    print(f"f_warmup {tuple(f_warmup.shape)} -> forecast {tuple(preds.shape)}")
    print(f"MSE over {horizon} fully autoregressive steps: {mse:.2e}")

    if "--plot" in sys.argv:
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            print("matplotlib not installed - skipping plot")
        else:
            plt.figure(figsize=(9, 3))
            plt.plot(truth[0, :, 0], label="truth")
            plt.plot(preds[0, :, 0], "--", label="forecast")
            plt.legend()
            plt.title("Two-phase autoregressive forecast")
            plt.tight_layout()
            plt.show()

    # ------------------------------------------------------------------
    # 2. return_warmup
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("2. return_warmup=True")
    print("=" * 70)

    full = model.forecast(f_warmup, horizon=horizon, return_warmup=True)
    print(f"forecast(...)                    -> {tuple(preds.shape)}")
    print(f"forecast(..., return_warmup=True) -> {tuple(full.shape)}")
    print("The first 200 steps are the teacher-forced warmup outputs — handy")
    print("for plotting the transition from teacher forcing to autoregression.")

    # ------------------------------------------------------------------
    # 3. Drivers with correct time alignment
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("3. Input-driven forecasting: driver alignment")
    print("=" * 70)
    print(
        """
Training pairs (feedback_t, driver_t) -> feedback_{t+1}. The forecast loop
keeps that pairing, which fixes the alignment of forecast_inputs:

  warmup window   [w0 ............ w1)   warmup feedback AND warmup drivers
  forecast window [w1 ... w1+horizon)    drivers continue at w1, feedback is
                                         generated by the model itself

  - forecast drivers start at the first step AFTER the warmup window
  - they need horizon-1 steps (the step-0 driver was consumed in warmup);
    passing horizon steps is fine too, the last one is unused
"""
    )

    # System whose next value depends on an exogenous driver:
    #   x_{t+1} = 0.9 x_t + 0.5 d_t,   d_t known in advance
    n = 1400
    d = torch.sin(0.05 * torch.arange(n, dtype=torch.float32)).reshape(1, -1, 1)
    x = torch.zeros(1, n, 1)
    for i in range(n - 1):
        x[0, i + 1, 0] = 0.9 * x[0, i, 0] + 0.5 * d[0, i, 0]
    # x: (1, 1400, 1) feedback series, d: (1, 1400, 1) driver series

    feedback = Input((100, 1))
    driver = Input((100, 1))
    states = ESNLayer(200, feedback_size=1, input_size=1, spectral_radius=0.8)(feedback, driver)
    out = CGReadoutLayer(200, 1, name="output")(states)
    driven = ESNModel([feedback, driver], out)

    # Train: inputs at t, target at t+1 — for feedback AND driver alike
    ESNTrainer(driven).fit(
        warmup_inputs=(x[:, :200], d[:, :200]),
        train_inputs=(x[:, 200:1000], d[:, 200:1000]),
        targets={"output": x[:, 201:1001]},
    )

    w0, w1 = 800, 1000  # forecast-warmup window
    horizon = 300
    preds = driven.forecast(
        (x[:, w0:w1], d[:, w0:w1]),  # warmup: feedback + driver over [w0, w1)
        forecast_inputs=(d[:, w1 : w1 + horizon - 1],),  # drivers over the forecast window
        horizon=horizon,
    )
    truth = x[:, w1 : w1 + horizon]
    print(f"warmup [{w0}:{w1}), forecast drivers [{w1}:{w1 + horizon - 1}) (horizon-1 steps)")
    print(f"forecast {tuple(preds.shape)}, MSE = {torch.mean((preds - truth) ** 2).item():.2e}")
    print("Misaligned drivers are the #1 silent forecasting bug: shifting them")
    print("by one step trains fine but degrades the autoregressive forecast.")

    # ------------------------------------------------------------------
    # 4. Multi-output models
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("4. Multi-output forecasting")
    print("=" * 70)
    print("With several outputs, the FIRST one is fed back — its dimension")
    print("must match the feedback input. Other outputs ride along.")

    series3 = torch.cumsum(0.05 * torch.randn(1, 1201, 3), dim=1)  # (1, 1201, 3)
    inp = Input((100, 3))
    states = ESNLayer(250, feedback_size=3)(inp)
    main_out = CGReadoutLayer(250, 3, name="main")(states)  # fed back (3 == feedback)
    aux_out = CGReadoutLayer(250, 1, name="aux")(states)  # auxiliary scalar
    multi = ESNModel(inp, outputs=[main_out, aux_out])

    ESNTrainer(multi).fit(
        warmup_inputs=(series3[:, :200],),
        train_inputs=(series3[:, 200:1000],),
        targets={
            "main": series3[:, 201:1001],  # next-step prediction
            "aux": series3[:, 200:1000].norm(dim=-1, keepdim=True),  # state norm
        },
    )

    main_pred, aux_pred = multi.forecast(series3[:, 800:1000], horizon=100)
    print(f"main (feedback) forecast: {tuple(main_pred.shape)}")
    print(f"aux             forecast: {tuple(aux_pred.shape)}")

    print("\nDone. Ensembles of forecasters: 07_ensembles.py")


if __name__ == "__main__":
    main()
